version = 1

exclude_patterns = [
  '**/examples/**'
]

[[transformers]]
    name = "prettier"
    enabled = true

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  plugins = ["vue", "react", "ember"]
  module_system = "es-modules"
  environment = ["nodejs"]
  dialect = "typescript"
