version = 1

exclude_patterns = [
  '**/examples/**'
]

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  plugins = ["react"]
  style_guide = "standard"
  environment = ["nodejs", "browser", "jest", "mongo"]
  dialect = "typescript"
